# Generated by Django 3.2.12 on 2022-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(choices=[('presant', 'presant'), ('abscent', 'abscent')], default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_heading', models.CharField(max_length=500)),
                ('task_description', models.TextField(max_length=4000)),
                ('note', models.CharField(max_length=1000)),
                ('belongs_to', models.CharField(max_length=70)),
            ],
        ),
    ]
