# Generated by Django 3.2.12 on 2022-06-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internapp', '0002_alter_attendence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('taskname', models.CharField(max_length=70)),
                ('taskfile', models.FileField(upload_to='internapp/image')),
            ],
        ),
    ]
