# Generated by Django 3.2.12 on 2022-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internapp', '0003_tasksubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmit',
            name='taskfile',
            field=models.FileField(upload_to='image/'),
        ),
    ]
